### PR TITLE
Completed css-two-column-layout

### PR DESCRIPTION
**Pull request by kevin-l1**
image

### CODE REVIEW

**Review by shawnkost — CHANGES_REQUESTED** [review]
You're missing the "Learn more" button, and the font doesn't look like the image. Make sure you're comparing your example to our example. Looks like you are missing one of the fonts we provided for you

**Review by shawnkost — CHANGES_REQUESTED** [review]
Fonts still don't seem like they match. Compare your picture to ours.

**Review by shawnkost — CHANGES_REQUESTED** [review]
Please include an updated screenshot of the page, so I can verify that the fonts match

**Comment by kevin-l1** [comment]
> Please include an updated screenshot of the page, so I can verify that the fonts match

Changed the screenshot.

**Pull request merged**
